CREATE TABLE motivational_posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('video', 'image')),
  media_url TEXT NOT NULL,
  caption TEXT,
  author_name TEXT,
  author_avatar_url TEXT
);

-- Enable Row Level Security
ALTER TABLE motivational_posts ENABLE ROW LEVEL SECURITY;

-- Create a policy that allows logged-in users to read all posts
CREATE POLICY "Allow logged-in users to read motivational posts"
ON motivational_posts
FOR SELECT
TO authenticated
USING (true);
