-- Tabla de comentarios con soporte para respuestas anidadas
CREATE TABLE post_comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Relación con el post
  post_id BIGINT NOT NULL REFERENCES motivational_posts(id) ON DELETE CASCADE,
  
  -- Usuario que comenta
  user_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Contenido del comentario
  comment_text TEXT NOT NULL,
  
  -- Soporte para comentarios anidados (respuestas)
  parent_comment_id BIGINT REFERENCES post_comments(id) ON DELETE CASCADE,
  
  -- Validación
  CONSTRAINT comment_text_not_empty CHECK (char_length(trim(comment_text)) > 0),
  CONSTRAINT comment_text_max_length CHECK (char_length(comment_text) <= 500)
);

-- Índices para mejorar performance
CREATE INDEX idx_post_comments_post_id ON post_comments(post_id);
CREATE INDEX idx_post_comments_user_id ON post_comments(user_id);
CREATE INDEX idx_post_comments_parent ON post_comments(parent_comment_id);
CREATE INDEX idx_post_comments_created_at ON post_comments(created_at DESC);

-- Trigger para actualizar updated_at
CREATE OR REPLACE FUNCTION update_post_comments_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_update_post_comments_updated_at
BEFORE UPDATE ON post_comments
FOR EACH ROW
EXECUTE FUNCTION update_post_comments_updated_at();

-- Row Level Security
ALTER TABLE post_comments ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Anyone can read comments"
ON post_comments FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can create comments"
ON post_comments FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own comments"
ON post_comments FOR UPDATE
TO authenticated
USING (auth.uid() = user_id)
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own comments"
ON post_comments FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
