-- Tabla para sistema de seguir usuarios
CREATE TABLE user_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Usuario que sigue
  follower_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Usuario que es seguido
  following_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Evitar que un usuario se siga a sí mismo
  CONSTRAINT no_self_follow CHECK (follower_id != following_id),
  
  -- Evitar duplicados
  CONSTRAINT unique_follow UNIQUE (follower_id, following_id)
);

-- Índices para mejorar performance
CREATE INDEX idx_user_follows_follower ON user_follows(follower_id);
CREATE INDEX idx_user_follows_following ON user_follows(following_id);

-- Row Level Security
ALTER TABLE user_follows ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Anyone can read follows"
ON user_follows FOR SELECT
TO authenticated
USING (true);

CREATE POLICY "Users can follow others"
ON user_follows FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = follower_id);

CREATE POLICY "Users can unfollow"
ON user_follows FOR DELETE
TO authenticated
USING (auth.uid() = follower_id);

-- Función para obtener conteo de seguidores/siguiendo
CREATE OR REPLACE FUNCTION get_user_follow_stats(p_user_id UUID)
RETURNS TABLE (
  followers_count BIGINT,
  following_count BIGINT
) AS $$
BEGIN
  RETURN QUERY
  SELECT
    (SELECT COUNT(*) FROM user_follows WHERE following_id = p_user_id) AS followers_count,
    (SELECT COUNT(*) FROM user_follows WHERE follower_id = p_user_id) AS following_count;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION get_user_follow_stats(UUID) TO authenticated;

-- Función para verificar si un usuario sigue a otro
CREATE OR REPLACE FUNCTION is_following(p_follower_id UUID, p_following_id UUID)
RETURNS BOOLEAN AS $$
BEGIN
  RETURN EXISTS (
    SELECT 1 FROM user_follows
    WHERE follower_id = p_follower_id AND following_id = p_following_id
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION is_following(UUID, UUID) TO authenticated;
