-- Tabla de notificaciones
CREATE TABLE notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  
  -- Usuario que recibe la notificación
  recipient_id UUID NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Usuario que genera la acción (puede ser NULL para notificaciones del sistema)
  actor_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Tipo de notificación
  type TEXT NOT NULL CHECK (type IN ('like', 'comment', 'follow', 'new_post', 'comment_reply')),
  
  -- Referencias a recursos relacionados
  post_id BIGINT REFERENCES motivational_posts(id) ON DELETE CASCADE,
  comment_id BIGINT REFERENCES post_comments(id) ON DELETE CASCADE,
  
  -- Estado
  read BOOLEAN DEFAULT FALSE NOT NULL,
  
  -- Mensaje opcional (para notificaciones del sistema)
  message TEXT
);

-- Índices para mejorar performance
CREATE INDEX idx_notifications_recipient ON notifications(recipient_id, read, created_at DESC);
CREATE INDEX idx_notifications_post ON notifications(post_id);
CREATE INDEX idx_notifications_actor ON notifications(actor_id);

-- Row Level Security
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Políticas RLS
CREATE POLICY "Users can read their own notifications"
ON notifications FOR SELECT
TO authenticated
USING (auth.uid() = recipient_id);

CREATE POLICY "Users can update their own notifications"
ON notifications FOR UPDATE
TO authenticated
USING (auth.uid() = recipient_id)
WITH CHECK (auth.uid() = recipient_id);

CREATE POLICY "Users can delete their own notifications"
ON notifications FOR DELETE
TO authenticated
USING (auth.uid() = recipient_id);

-- Función para marcar todas las notificaciones como leídas
CREATE OR REPLACE FUNCTION mark_all_notifications_read(p_user_id UUID)
RETURNS void AS $$
BEGIN
  UPDATE notifications
  SET read = TRUE
  WHERE recipient_id = p_user_id AND read = FALSE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION mark_all_notifications_read(UUID) TO authenticated;

-- Función para obtener conteo de notificaciones no leídas
CREATE OR REPLACE FUNCTION get_unread_notifications_count(p_user_id UUID)
RETURNS BIGINT AS $$
BEGIN
  RETURN (
    SELECT COUNT(*)
    FROM notifications
    WHERE recipient_id = p_user_id AND read = FALSE
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

GRANT EXECUTE ON FUNCTION get_unread_notifications_count(UUID) TO authenticated;
